Repository NullFull/call22nd, pull requests merged in 2024-03, with the labels that each got.

#14 각종 링크 수정 및 `scrollToTop` 버튼 구현(3/15 프론트엔드 피드백 반영)
  public/images/top.svg
  src/app/layout.tsx
  src/app/main.css
  src/app/page.tsx
  src/components/Ask/FindByName.css
  src/components/ScrollToTop.tsx
  src/components/WhiteButtonTitle.tsx
Labels: enhancement

#18 Open Graph 이미지, ALT 텍스트 추가
  src/app/layout.tsx
  src/app/opengraph-image.alt.txt
  src/app/opengraph-image.png
Labels: enhancement

#20 0322 버전에 맞게 텍스트 수정 및 컴포넌트 위치 재조정
  src/app/main.css
  src/app/page.tsx
  src/components/PurpleButton.tsx
Labels: enhancement

#21 fix: add openGraph to metaData
  src/app/layout.tsx
Labels: enhancement

#17 후보자들의 응답 결과를 보여주는 컴포넌트 제작(call21st 코드 가져옴)
  src/app/main.css
  src/app/page.tsx
  src/components/Result.tsx
  src/components/ScrollToTop.tsx
  src/components/result.css
Labels: enhancement

#22 3/22 버전 배포
  package.json
  pages/_app.js
  pages/answer.css
  pages/answer.js
  pages/layout.css
  src/app/layout.tsx
  src/app/main.css
  src/app/opengraph-image.alt.txt
  src/app/opengraph-image.png
  src/app/page.tsx
  src/components/PurpleButton.tsx
  src/components/Result.tsx
  src/components/ScrollToTop.tsx
  src/components/result.css
  yarn.lock
Labels: enhancement

#32 Feature: Google Analytics 추가
  package.json
  src/app/layout.tsx
  yarn.lock
Labels: enhancement

#33 feat: Google Analytics 추가 & 문구 및 글자 크기 수정
  package.json
  src/app/layout.tsx
  src/app/main.css
  src/app/page.tsx
  src/components/PurpleButton.tsx
  yarn.lock
Labels: bug, enhancement

#34 misc: 텍스트 수정
  src/app/page.tsx
Labels: enhancement

#35 fix: 텍스트 색을 검정색으로 바로잡음
  src/components/Ask/Candidates.css
  src/components/Ask/Candidates.js
Labels: bug

#38 [Style] PC 스타일 대응 및 각종 스타일 수정
  public/images/bell.png
  public/images/bell.webp
  public/images/law.png
  public/images/page.svg
  public/images/qna.png
  public/images/speaker.webp
  public/images/top.svg
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/main.css
  src/app/page.tsx
  src/components/Ask/Candidates.css
  src/components/Ask/Candidates.js
  src/components/Ask/FindByName.css
  src/components/Ask/FindByParty.css
  src/components/Ask/FindByParty.js
  src/components/Ask/FindByRegion.css
  src/components/Ask/index.css
  src/components/Ask/index.js
  src/components/Ask/tabstyle.css
  src/components/Logo.tsx
  src/components/PurpleButton.tsx
  src/components/ScrollToTop.tsx
  src/components/Stats.tsx
Labels: enhancement

#41 refact: `ask()` 함수의 `candidate.checked` 를 체크하는 로직 추가
  src/components/Ask/index.js
Labels: bug

#44 fix: 모바일에서 후보를 불러왔을 때 가로 스크롤이 제대로 되지 않는 문제 수정 & 이메일 변경
  src/app/page.tsx
  src/components/Ask/Candidates.css
Labels: bug

#43 `ReactStrictMode`를 `false`로 수정하여 `localhost`에서 `TOGGLE_ITEM` 내 함수 호출이 두번씩 되던 문제 해결
  next.config.js
Labels: bug

#52 feat: OG 변경
  src/app/opengraph-image.alt.txt
  src/app/opengraph-image.png
Labels: enhancement
